# Машинное обучение, HR-TECH

## НИУ ВШЭ, 2024-2025 уч. год

### Домашнее задание №1. Библиотека Numpy

### О задании

В данном домашнем задании вы попрактикуетесь в работе с библиотекой numpy!

In [ ]:
import numpy as np

Во всех задачах необходимо написать код решения внутри функции и проверить его работу, вызвав функцию для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`.

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`.

# Иногда при выводе итоговых массивов Colab сворачивает середину массивов ответов в многоточия в задачах 2 и 9. Чтобы этого не происходило - устанавливаем вывод неограниченного числа знаков при помощи функции
np.set_printoptions(threshold=np.inf)

### 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам для некоторого курса. Пусть для этого курса вес экзамена равен 0.35, вес домашек - 0.4, вес проекта - 0.15, вес аудиторки - 0.1. Тогда, например, если экзамен написан на 6, домашки сданы на 9, проект закрыт на 8, а оценка за аудиторку 7 - итоговая оценка будет отлично - 8

In [ ]:
def result_mark(weights, marks):
    # your code here
    result = round(np.sum(weights * marks))
    return result

In [ ]:
weights = np.array([0.35, 0.4, 0.15, 0.1])
marks = np.array([6, 9, 8, 7])
result_mark(weights, marks)

8

### 2

Напишите функцию, меняющую каждое третье (начиная с 0) значение массива целых чисел на заданное число. Например, если на вход поступает массив `array([3, 5, 1, 0, -3, 22, 213436])` и число `-111`, то на выходе должен получиться массив `array([-111, 5, 1, -111, -3, 22, -111])`.

In [ ]:
def change_array(array, number):
    # your code here
    array[::3] = number
    return array

In [ ]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111
change_array(array, number)

array([-111,    5,    1, -111,   -3,   22, -111])

### 3

Напишите функцию, выдающую индексы «близких» элементов заданных массивов, а именно тех пар элементов, чей модуль разницы не превосходит заданного значения. Например, если на вход поступают массив `array([1.5, 0.5, 2, -4.1, -3, 6, -1])`, массив `array([1.2, 0.5, 1, -4, 3, 0, -1.2])` и число `0.5`, то на выходе должен получиться массив `array([0, 1, 3, 6])` (_**важно: не `tuple`, а одномерный массив типа `numpy.ndarray` (то есть `.ndim` от него равно 1)!**_).

In [ ]:
def find_close(array1, array2, precision):
    # your code here
    array3 = abs(array1 - array2)     # Создаем массив из модулей попарных разностей изначально заданных массивов array1 и array2
    array4 = np.where(array3 <= precision)[0]  # Создаем булев массив выполнения логического условия (разности не больше заданного числа) и собираем в отдельный массив номера элементов, где условие выполняется, т.е. номера элементов True
    print(type(array4))                # Проверяем тип массива
    return array4


In [ ]:
array3 = abs(array1 - array2)    # Проверки содержимого массивов промежуточных вычислений и типа массива результата
print(array3)
array4 = array3 <= precision
print(array4)
array5 = np.where(array4)[0]
print(array5)
type(array5)

[0.3 0.  1.  0.1 6.  6.  0.2]
[ True  True False  True False False  True]
[0 1 3 6]


numpy.ndarray

In [ ]:
array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4, 3, 0, -1.2])
precision = 0.5
find_close(array1, array2, precision)


<class 'numpy.ndarray'>


array([0, 1, 3, 6])

### 4

Напишите функцию, которая составляет блочную матрицу из четырех блоков, где каждый блок - это заданная матрица. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
\end{pmatrix},
$$
то ответом будет матрица
$$
\begin{pmatrix}
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
\end{pmatrix}
$$

In [ ]:
def block_matrix(block):
    # your code here
    block2 = np.hstack((block, block))
    block3 = np.vstack((block2, block2))
    return block3

In [ ]:
block = np.array([[0, 1, 2], [3, 4, 5]])
block_matrix(block)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### 5

Напишите функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix},
$$
то ответом будет 32.

In [ ]:
def diag_prod(matrix):
    # your code here
   n = matrix.shape[1]
   matrix1 = matrix != 0
   matrix2 = np.identity(n) == 1
   matrix3 = matrix1 * matrix2
   matrix4 = matrix * matrix3
   s = np.prod(matrix4[matrix4!=0])
   return s

In [ ]:
matrix1 = matrix != 0 # Создаем булев массив на основе заданной матрицы, где все ненулевые элементы маркируются True
print(matrix1)
n = matrix.shape[0] # Проверка размерности изначально заданной квадратной матрицы (количество строк = количеству столбцов = n). Для универсальности ставим [1] - количество именно столбцов
print(n)
matrix2 = np.identity(n) == 1 # Создаем единичную матрицу размерности n и превращаем ее в булеву матрицу с True на главной диагонали
print(matrix2)
matrix3 = matrix1 * matrix2  # Создаем булеву матрицу, у которой True - ненулевые элементы главной диагонали
print(matrix3)
matrix4 = matrix * matrix3   # Матрица, у которой ненулевые только элементы главной диагонали начальной матрицы
print(matrix4)
matrix5 = matrix4[matrix4 != 0] # Составляем массив из ненулевых элементов главной диагонали исходной матрицы
print(matrix5)
s = np.prod(matrix5) # Находим произведение ненулевых элементов главной диагонали исходной маотрицы
print(s)

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]
3
[[ True False False]
 [False  True False]
 [False False  True]]
[[False False False]
 [False  True False]
 [False False  True]]
[[0 0 0]
 [0 4 0]
 [0 0 8]]
[4 8]
32


In [ ]:
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
diag_prod(matrix)

32

### 6

Для улучшения качества работы некоторых алгоритмов машинного обучения может быть полезно использовать [нормализацию данных](https://vk.cc/8xmfQk), чтобы привести признаки в выборке к одному масштабу — а именно, из каждого столбца вычесть среднее его значений и поделить на их стандартное отклонение. Напишите функцию, нормализующую входящую матрицу (по столбцам). Например, если на вход подается матрица
$$
\begin{pmatrix}
1 & 4 & 4200\\
0 & 10 & 5000\\
1 & 2 & 1000\\
\end{pmatrix},
$$
то результатом с точностью до сотых будет матрица
$$
\begin{pmatrix}
0.71 & -0.39 & 0.46\\
-1.41 & 1.37 & 0.93\\
0.71 & -0.98 & -1.39\\
\end{pmatrix}
$$

_Подсказка. Учтите, что в вашей матрице не должно получаться никаких nan. Подумайте, в каком случае они могут возникнуть и как обойти эту проблему._


In [ ]:
def normalize(matrix):
    # your code here
    n = matrix.shape[0]
    vec1 = np.mean(matrix, axis=0)
    vec2 = np.std(matrix, axis=0)
    vec2[vec2 == 0] = 1
    matrix1 = (matrix - vec1) / vec2
    np.set_printoptions(2, True)
    return matrix1

Несуществующие значения (nan) могут возникнуть, если стандартное отклонение по столбцу равно нулю. Это значит, что все значения в столбце - одинаковые и равны среднему значению. В этом случае нормализация может выполняться следующим образом: 1. Обнуляем столбец 2. Оставляем без изменений (т.к. они уже все одинаковые), 3. Заменяем все значения столбца на другое (ненулевое и не изначальное) число.
Чтобы получить столбец нулевых значений вместо nan нужно нулевой элемент строки со стандартными отклонениями заменить на 1 (нули в итоговой матрице получатся, т.к. каждый элемент равен средней по столбцу).
Если нужно, чтобы нормализованный столбец был не нулевым - нужно прибавить к полученному нулевому столбцу желаемое число.
В данном решении идем по первому варианту - заменяем nan на 0.

In [ ]:
n = matrix.shape[0] # Считаем количество строк в исходной матрице
print(n)
vec1 = np.mean(matrix, axis=0) # Вычисляем вектор-строку с средними значениями по столбцам
vec2 = np.std(matrix, axis=0) # Вычисляем вектор-строку co стандартным отклонением по столбцам
vec2[vec2 == 0] = 1 # Подстраховываемся на случай неопределенности (нулевого стандартного отклонения) - заменяем 0 на 1 (в этом случае столбец итоговой матрицы будет нулевым)
matrix1  = (matrix - vec1) / vec2  # Используя бродкаст, отнимаем от каждого элемента столбца соответствующее среднее и делим разность на стандартное отклонение
np.set_printoptions(2, True) # Настраиваем параметры вывода - 2 знака после запятой, отключаем научную нотацию для малых чисел для отображения в стандартной десятичной форме
print(vec1)
print(vec2)
print(matrix1)

3
[   0.67    5.33 3400.  ]
[   0.47    3.4  1728.2 ]
[[ 0.71 -0.39  0.46]
 [-1.41  1.37  0.93]
 [ 0.71 -0.98 -1.39]]


In [ ]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])
normalize(matrix)

array([[ 0.71, -0.39,  0.46],
       [-1.41,  1.37,  0.93],
       [ 0.71, -0.98, -1.39]])

### 7

Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.

In [ ]:
def antiderivative(coefs): #альтернативное решение с применением функции np.polyint()
    # your code here
    vec1 = np.polyint(coefs)
    vec2 = np.append(vec1[:-1], -2)
    return vec2


In [ ]:
def antiderivative(coefs): # Первоначальное решение, разобранное на семинаре
    # your code here
    n1 = np.arange(1, coefs.shape[0] + 1)[::-1]
    res = coefs / n1
    coefs1 = np.append(res, -2)
    return coefs1

In [ ]:
vec1 = np.polyint(coefs)   # Функция, возвращающая коэффициенты первообразной к заданному массиву коэффициентов изначально заданного полинома (константа-свободный член выводится как 0))
print(vec1)
vec2 = np.append(vec1[:-1], 22) # Обрезаем нулевой коэффициент, добавляем произвольное число C (например, 22)
print(vec2)


[1. 2. 0. 1. 0.]
[ 1.  2.  0.  1. 22.]


In [ ]:
coefs = np.array([4, 6, 0, 1])
antiderivative(coefs)

array([ 1.,  2.,  0.,  1., -2.])

### 8

Напишите функцию, делающую данную [треугольную матрицу](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) симметричной. Например, если на вход поступает матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$
то на выходе должна быть матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

In [ ]:
def make_symmetric(matrix):
    # your code here
    matrix1 = matrix.T      # Транспонируем исходную матрицу
    n = matrix.shape[0]   # В последующих 3 строках составляем матрицу из элементов главной диагонали исходной матрицы
    matrix2 = np.identity(n) == 1
    matrix3 = matrix * matrix2
    matrix4 = matrix1 + matrix - matrix3 # Находим искомую матрицу как сумму исходной, транспонированной и разности элементов главной диагонали (чтобы избежать задваивания главной диагонали)
    return matrix4

In [ ]:
n = matrix.shape[0] # Проверка размерности изначально заданной матрицы (т.к. треугольная матрица по определению - частный случай квадратной, то количество строк = количеству столбцов = n)
print(n)
matrix2 = np.identity(n) == 1 # Создаем единичную матрицу размерности n и превращаем ее в булеву матрицу с True на главной диагонали
print(matrix2)
matrix3 = matrix * matrix2 # Матрица, у которой ненулевые только элементы главной диагонали начальной матрицы
print(matrix3)

4
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ 1  0  0  0]
 [ 0  5  0  0]
 [ 0  0  8  0]
 [ 0  0  0 10]]


In [ ]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
make_symmetric(matrix)

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 3,  6,  8,  9],
       [ 4,  7,  9, 10]])

### 9

Напишите функцию, создающую прямоугольную матрицу из m одинаковых строк, заполненных последовательными натуральными числами от a до b включительно в возрастающем порядке. Например, если m = 5, a = 3, b = 10, то на выходе будет матрица
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

In [ ]:
def construct_matrix(m, a, b):
    # your code here
    vec = np.arange(a, b+1)
    matrix1 = np.zeros((m, b+1-a), dtype=int)
    matrix2 = vec + matrix1
    return matrix2

In [ ]:
vec = np.arange(a, b+1)                   # Создаем вектор-строку c равномерно распределенными значениями от a до b включительно
print(vec)
matrix1 = np.zeros((m, b+1-a), dtype=int) # Создаем нулевую матрицу с m строк и количеством столбцов, равным количеству значений в интервале от a до b.
print(matrix1)
matrix2 = vec + matrix1                   # Применяем бродкаст
print(matrix2)

[ 3  4  5  6  7  8  9 10]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]]


In [ ]:
m = 5
a = 3
b = 10
construct_matrix(m, a, b)

array([[ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

### 10

Напишите функцию, вычисляющую [косинусную близость](https://en.wikipedia.org/wiki/Cosine_similarity) двух векторов. Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет -0.25.

In [ ]:
def cosine_similarity(vec1, vec2):
    # your code here
    n1 = np.dot(vec1, vec2)
    n2 = np.dot(vec1, vec1) ** 0.5
    n3 = np.dot(vec2, vec2) ** 0.5
    n4 = n1 / (n2 * n3)
    return n4

In [ ]:
n1 = np.dot(vec1,vec2)        # Находим скалярное произведение векторов vec1 и vec2. Также скалярное произведение можно посчитать через сумму произведений координат np.sum(vec1*vec2)
print(n1)
n2 = np.dot(vec1, vec1) ** 0.5  # Находим вторую норму (длину) вектора vec1. Квадрат второй нормы также можно посчитать через np.sum(vec1*vec1)
print(n2)
n3 = np.dot(vec2, vec2) ** 0.5  # Находим вторую норму (длину) вектора vec2 (по аналогии с vec1). Также для этого можно использовать np.linalg.norm(vec2)
print(n3)
n4 = n1 / (n2 * n3)           # Вычисляем косинусную близость векторов vec1 и vec2
print(n4)
n5 = np.sum(vec1*vec1) ** 0.5
print(n5)
n6 = np.linalg.norm(vec2)
print(n6)


-24
8.0
12.0
-0.25
8.0
12.0


In [ ]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(vec1, vec2)

-0.25